name: moviest
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.6
  objectbox: ^2.3.1
  objectbox_flutter_libs: ^2.3.1
  path: ^1.8.3
  path_provider: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  objectbox_generator: any

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
